swagger: "2.0"
info:
  description: ICNDB sample API for ITB
  title: icndb
  version: 0.0.1
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api
paths:
  /jokes/count:
    get:
      summary: Get the count of the available jokes
      operationId: getJokesCount
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/CountResponse'
  /jokes/random:
    get:
      summary: Get a random joke
      operationId: getRandomJoke
      parameters:
        - name: firstName
          in: query
          description: Name to replace Chuck with in Joke
          type: string
          required: false
        - name: lastName
          in: query
          description: Name to replace Norris with in Joke
          type: string
          required: false
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/FactResponse'
  /jokes/{id}:
    get:
      summary: Get the joke with the specified id
      operationId: Get joke by id
      parameters:
        - name: id
          in: path
          description: Joke ID
          type: integer
          required: true
        - name: firstName
          in: query
          description: Name to replace Chuck with in Joke
          type: string
          required: false
        - name: lastName
          in: query
          description: Name to replace Norris with in Joke
          type: string
          required: false
      responses:
        200:
          description: Ok
          schema:
            $ref: '#/definitions/FactResponse'
        404:
          description: Not found
  /system/hostname:
    get:
      summary: Get the hostname of the system
      operationId: getHostname
      responses:
        200:
          description: Got hostname
          schema:
            $ref: '#/definitions/HostnameResponse'
        500:
          description: Failed to get hostname
  /system/ipaddresses:
    get:
      summary: Get the IP addresses of the host
      operationId: getIPAddresses
      responses:
        200:
          description: Got IP addresses
          schema:
            $ref: '#/definitions/IPAddressesResponse'
  /deploy/env:
    get:
      summary: Get the deployment environment
      operationId: getDeployEnv
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/DeployEnvResponse'
  /health:
    get:
      summary: Check the health state of the service
      operationId: getHealth
      responses:
        200:
          description: Service is healthy
        500:
          description: Service is not healty
definitions:
  CountResponse:
    type: object
    properties:
      count:
        type: integer
    required:
      - count
  FactResponse:
    type: object
    properties:
      id:
        type: integer
      joke:
        type: string
      categories:
        type: array
        items:
          type: string
    required:
      - joke
      - categories
  HostnameResponse:
    type: object
    properties:
      hostname:
        type: string
    required:
      - hostname
  IPAddressesResponse:
    type: object
    properties:
      addresses:
        type: array
        items:
          type: string
  DeployEnvResponse:
    type: object
    properties:
      env:
        type: string